[www]
; Usuario y grupo por defecto en Alpine para servicios web
user = nobody
group = nobody

; Escuchar en el puerto 9000 desde cualquier IP de la red interna
listen = 0.0.0.0:9000

; Gestión de procesos (cuántos "trabajadores" de PHP se levantan)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; IMPORTANTE: Permitir que PHP lea las variables de entorno del contenedor (.env)
clear_env = no