[www]
; User and group for the web service in Alpine Linux.
user = nobody
group = nobody

; Listen port 9000 from any IP on the internal network
listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Read env vars from the container
clear_env = no

; Enable error logging
catch_workers_output = yes
php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on
php_flag[display_errors] = on