global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Scrape metrics from MariaDB Exporter
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  # Scrape internal Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
