server.document-root = "/var/www/localhost/htdocs"
server.port = 1337
server.username = "lighttpd"
server.groupname = "lighttpd"

index-file.names = ( "index.html" )

# Setup basic mime types
mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".css" => "text/css",
  ".js" => "application/x-javascript",
  ".jpg" => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".gif" => "image/gif",
  ".png" => "image/png",
  "" => "application/octet-stream"
)
