# Base image
FROM debian:bookworm

# Dependencies
RUN apt-get update && apt-get install -y \
	mariadb-server \
	&& rm -rf /var/lib/apt/lists/*

# Configuration files & scripts
COPY conf/my.cnf /etc/mysql/conf.d/my.cnf
COPY tools/db-setup.debian.sh /usr/local/bin/db-setup.sh

# Execute permission
RUN chmod +x /usr/local/bin/db-setup.sh

# Listen port
EXPOSE 3306

# Run container PID 1
ENTRYPOINT ["/usr/local/bin/db-setup.sh"]