events {
    # Configuración básica de conexiones simultáneas
    worker_connections 1024;
}

http {
    # Incluye los tipos de archivos estándar (para que los CSS y JS carguen bien)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # 1. Puertos y seguridad (REGLA DEL SUBJECT)
        listen 443 ssl;
        listen [::]:443 ssl;

        # 2. Nombre de dominio
        server_name serjimen.42.fr;

        # 3. Certificados TLS que generamos en el Dockerfile
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # 4. Protocolos permitidos (REGLA DEL SUBJECT)
        ssl_protocols TLSv1.2 TLSv1.3;

        # 5. Directorio raíz donde están los archivos de WordPress
        root /var/www/html;
        index index.php index.html index.htm;

        # 6. Comportamiento por defecto al entrar a la web
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # 7. El puente mágico hacia PHP-FPM
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            
            # Nombre del contenedor de WordPress y su puerto interno
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}